github: firmware: add target job for required status checks
Status Checks (at least judging from the docs) don't support jobs without a name as well as job matrixes.

Therefore a single job seems to be required which is run once all builds have been successfull.

This should achieve that.

It can be added as "All Targets Build" in the rulesets.

Then Features like auto merge will wait until all builds have completed until they are executed.

diff --git a/.github/workflows/firmware.yml b/.github/workflows/firmware.yml
--- a/.github/workflows/firmware.yml
+++ b/.github/workflows/firmware.yml
@@ -68,6 +68,22 @@ jobs:
           name: ${{ matrix.target }}_output
           path: ./output
 
+  # Workarround job so that there is a single job for the required status check
+  build_firmware_complete:
+    name: All Targets Build
+    runs-on: ubuntu-22.04
+    if: ${{ always() }}
+    needs: [build_firmware]
+    steps:
+      - name: Error out if there is a failure
+        if: ${{ needs.build_firmware.result != 'success' }}
+        run: |
+          echo "One or more builds failed."
+          exit 1
+      - name: Proceed if all passed
+        if: ${{ needs.build_firmware.result == 'success' }}
+        run: echo "All required builds succeded!"
+
   create_release:
     runs-on: ubuntu-latest
     needs:
